
name: "Terraform"

on:
  push:
    paths:
    - 'terraform_aws/**'
    - '.github/workflows/terraform.yml'
    branches:
    - main
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform_aws
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1
       with:
         terraform_version: 1.3.9
         terraform_wrapper: false
     
     - name: Terraform Format
       id: fmt
       run: terraform fmt
       

     - name: Terraform Init
       id: init
       run: terraform init

     - name: Terraform Plan
       id: plan
       run: terraform plan -no-color

     - name: Terraform Apply
       if: "!contains(github.event.head_commit.message, 'destroy')"
       run: terraform apply -auto-approve

     - name: Terraform Destroy
       if: contains(github.event.head_commit.message, 'destroy')
       run: terraform destroy -auto-approve
